---
- name: Copying Files To Clients
  hosts: webservers
  tasks:
  - name: Check Free Space
    shell:
      cmd: df -h
    register: freespace
  - debug: var=freespace.stdout_lines

  - name: Copy the Large file
    copy:
      src: /home/ubuntu/ans_dir/sample_create.txt
      dest: /tmp/new/
    register: copy
  - debug: var=copy.stdout_lines


