Resources:
  InstanceSecurityGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to client host
      SecuirtyGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIP: 0.0.0.0/0
        - IpProtocol: tcp
            FromPort: *
            ToPort: 8080
            CidrIP: 0.0.0.0/0
        - IpProtocol: tcp
            FromPort: *
            ToPort: 8181
            CidrIP: 0.0.0.0/0
        - IpProtocol: tcp
            FromPort: *
            ToPort: 8005
            CidrIP: 0.0.0.0/0
  InstanceNode:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.large
      ImageId: ami-0959e8feedaf156bf # Ubuntu Server 18.04 LTS AMI
      UserData:
        'Fn::Base64':
          !Sub |
            # Update dependencies
            sudo apt-get update
            sudo apt-get dist-upgrade

            # ufw checkin
            apt-get install ufw
            ufw allow 8181
            ufw allow 8005
            ufw allow 8080
            ufw enable

            # Ansible Installation
            apt-get install ansible -y
      SecurityGroups:
        - !Ref InstanceSecurityGroups
      Tags:
        - Key: Name
          Value: JIRA EC2 Instance
        - Key: Type
          Value: JIRA Server
  DatabaseSecurityGroups:
    Type: AWS::RDS::DBsecurityGroup
    Properties:
      GroupDescription: Database Security Group
      DBSecurityGroupIngress:
        - CidrIP: 0.0.0.0/0
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: "JIRA Database"
      Engine: MySQL
      MasterUserName: JIRAadmin
      MasterUserPassword: tMXks28mRyBWpJni
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '5'
      DBSecurityGroups:
        - !Ref DatabaseSecurityGroups